#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#the "app_lucky_number" route name is not important yet
#app_MyPage:
#  path: /mypage
#  controller: App\Controller\MyPage::number